version: "3.8"

services:
  # PostgreSQL Database for Product Service
  product_db:
    image: postgres:15-alpine
    container_name: product_db_container
    restart: always
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PostgreSQL Database for Order Service
  order_db:
    image: postgres:15-alpine
    container_name: order_db_container
    restart: always
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PostgreSQL Database for Customer Service
  customer_db:
    image: postgres:15-alpine
    container_name: customer_db_container
    restart: always
    environment:
      POSTGRES_DB: customers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - customer_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d customers"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Product Microservice (FastAPI)
  product_service:
    build:
      context: ./backend/product_service
      dockerfile: Dockerfile
    container_name: product_api_container
    restart: always
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: product_db
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      product_db:
        condition: service_healthy
    volumes:
      - ./backend/product_service/app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  # Order Microservice (FastAPI)
  order_service:
    build:
      context: ./backend/order_service
      dockerfile: Dockerfile
    container_name: order_api_container
    restart: always
    ports:
      - "8001:8000"
    environment:
      POSTGRES_HOST: order_db
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PRODUCT_SERVICE_URL: http://product_service:8000
    depends_on:
      order_db:
        condition: service_healthy
      product_service:
        condition: service_started
    volumes:
      - ./backend/order_service/app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  # Customer Microservice (FastAPI)
  customer_service:
    build:
      context: ./backend/customer_service
      dockerfile: Dockerfile
    container_name: customer_api_container
    restart: always
    ports:
      - "8002:8000"
    environment:
      POSTGRES_HOST: customer_db
      POSTGRES_DB: customers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      customer_db:
        condition: service_healthy
    volumes:
      - ./backend/customer_service/app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  # Frontend (Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    restart: always
    ports:
      - "3000:80"
    environment:
      PRODUCT_API_BASE_URL: "http://product_service:8000"
      ORDER_API_BASE_URL: "http://order_service:8000"
      CUSTOMER_API_BASE_URL: "http://customer_service:8000"
    depends_on:
      product_service:
        condition: service_started
      order_service:
        condition: service_started
      customer_service:
        condition: service_started
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  product_db_data:
  order_db_data:
  customer_db_data:
