apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db
  namespace: sit722-staging
  labels: { app: customer-db }
spec:
  replicas: 1
  selector: { matchLabels: { app: customer-db } }
  template:
    metadata: { labels: { app: customer-db } }
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          valueFrom: { secretKeyRef: { name: app-secrets, key: POSTGRES_USER } }
        - name: POSTGRES_PASSWORD
          valueFrom: { secretKeyRef: { name: app-secrets, key: POSTGRES_PASSWORD } }
        - name: POSTGRES_DB
          valueFrom: { secretKeyRef: { name: app-secrets, key: POSTGRES_DB_CUSTOMER } }
        ports: [{ containerPort: 5432 }]
        volumeMounts: [{ name: data, mountPath: /var/lib/postgresql/data }]
      volumes:
      - name: data
        emptyDir: {}   # swap to PVC later for prod persistence
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db
  namespace: sit722-staging
spec:
  selector: { app: customer-db }
  ports: [{ port: 5432, targetPort: 5432 }]
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db
  namespace: sit722-prod
  labels: { app: customer-db }
spec:
  replicas: 1
  selector: { matchLabels: { app: customer-db } }
  template:
    metadata: { labels: { app: customer-db } }
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          valueFrom: { secretKeyRef: { name: app-secrets, key: POSTGRES_USER } }
        - name: POSTGRES_PASSWORD
          valueFrom: { secretKeyRef: { name: app-secrets, key: POSTGRES_PASSWORD } }
        - name: POSTGRES_DB
          valueFrom: { secretKeyRef: { name: app-secrets, key: POSTGRES_DB_CUSTOMER } }
        ports: [{ containerPort: 5432 }]
        volumeMounts: [{ name: data, mountPath: /var/lib/postgresql/data }]
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db
  namespace: sit722-prod
spec:
  selector: { app: customer-db }
  ports: [{ port: 5432, targetPort: 5432 }]
  type: ClusterIP
