apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: sit722-prod
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sit72210dacr.azurecr.io/frontend:latest
        ports:
          - containerPort: 80
        imagePullSecrets:
          - name: acr-secret
        volumeMounts:
          - name: frontend-config-volume
            mountPath: /usr/share/nginx/html/env.js
            subPath: env.js
      volumes:
        - name: frontend-config-volume
          configMap:
            name: frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sit722-prod
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer