apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: sit722-prod
  labels: { app: order-service }
spec:
  replicas: 2
  selector: { matchLabels: { app: order-service } }
  template:
    metadata: { labels: { app: order-service } }
    spec:
      containers:
      - name: order-service
        image: sit72210dacr.azurecr.io/order-service:latest
        ports: [{ containerPort: 8000 }]
        env:
        - name: DATABASE_URL
          value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@order-db:5432/$(POSTGRES_DB_ORDER)
        envFrom:
        - configMapRef: { name: app-config }
        - secretRef:    { name: app-secrets }
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: sit722-prod
spec:
  selector: { app: order-service }
  ports: [{ port: 80, targetPort: 8000 }]
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: sit722-prod
  labels: { app: order-service }
spec:
  replicas: 3
  selector: { matchLabels: { app: order-service } }
  template:
    metadata: { labels: { app: order-service } }
    spec:
      containers:
      - name: order-service
        image: 10.2dacr.azurecr.io/order-service:latest
        ports: [{ containerPort: 8000 }]
        env:
        - name: DATABASE_URL
          value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@order-db:5432/$(POSTGRES_DB_ORDER)
        envFrom:
        - configMapRef: { name: app-config }
        - secretRef:    { name: app-secrets }
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: sit722-prod
spec:
  selector: { app: order-service }
  ports: [{ port: 80, targetPort: 8000 }]
  type: ClusterIP
