name: CD Pipeline - Staging

on:
  workflow_run:
    workflows: ["CI Pipeline - Stage 1"]
    types:
      - completed

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group sit72210d-rg --name sit72210d-aks --overwrite-existing

      - name: Deploy to staging namespace
        run: |
          kubectl apply -f k8s/namespace-staging.yaml
          kubectl apply -f k8s/frontend.yaml -n 10.2d-staging
          kubectl apply -f k8s/customer-service.yaml -n 10.2d-staging
          kubectl apply -f k8s/product-service.yaml -n 10.2d-staging
          kubectl apply -f k8s/order-service.yaml -n 10.2d-staging
          kubectl apply -f k8s/rabbitmq.yaml -n 10.2d-staging

      - name: Wait for services to be ready
        run: kubectl rollout status deployment/frontend -n 10.2d-staging

      # Manual verification step (placeholder)
      - name: Pause for manual acceptance testing
        run: echo "✅ Staging environment deployed. Please run manual tests now."

      - name: Destroy staging environment
        if: always()
        run: kubectl delete namespace 10.2d-staging