name: CD Pipeline - Staging

on:
  workflow_run:
    workflows: ["CI Pipeline - Stage 1"]
    types:
      - completed

jobs:
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group 10.2d-rg --name sit722aks --overwrite-existing

      - name: Deploy to staging namespace
        run: |
          kubectl apply -f k8s/namespace-staging.yaml
          kubectl apply -f k8s/frontend.yaml -n sit722-staging
          kubectl apply -f k8s/customer-service.yaml -n sit722-staging
          kubectl apply -f k8s/product-service.yaml -n sit722-staging
          kubectl apply -f k8s/order-service.yaml -n sit722-staging
          kubectl apply -f k8s/rabbitmq.yaml -n sit722-staging

      - name: Wait for services
        run: kubectl rollout status deployment/frontend -n sit722-staging

      - name: Run acceptance tests
        run: echo "✅ Automated acceptance tests passed (placeholder)."

      - name: Destroy staging environment
        if: always()
        run: kubectl delete namespace sit722-staging