name: CD Pipeline - Stage 2 (Staging)

on:
  workflow_run:
    workflows: ["CI Pipeline - Stage 1"]
    types:
      - completed

jobs:
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: 10.2d-rg
      CLUSTER_NAME: sit722aks
      NAMESPACE: sit722-staging
      ACR_LOGIN_SERVER: sit72210dacr.azurecr.io
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

      - name: Deploy to Staging
        run: |
          kubectl apply -f k8s/staging/

      - name: Wait for frontend
        run: |
          kubectl rollout status deployment/frontend-deployment -n $NAMESPACE

      - name: Health check
        run: |
          FRONTEND_IP=$(kubectl get svc frontend -n $NAMESPACE -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          curl --fail http://$FRONTEND_IP || exit 1

      - name: Cleanup staging
        run: kubectl delete namespace $NAMESPACE