name: CI Pipeline

on:
  push:
    branches:
      - testing

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies & run tests
      run: |
        pip install pytest
        cd backend/customer_service && pip install -r requirements.txt && pytest
        cd ../product_service && pip install -r requirements.txt && pytest
        cd ../order_service && pip install -r requirements.txt && pytest

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: az acr login --name 10.2dacr

    - name: Build and push Docker images
      run: |
        docker build -t 10.2dacr.azurecr.io/frontend:latest ./frontend
        docker build -t 10.2dacr.azurecr.io/customer-service:latest ./backend/customer_service
        docker build -t 10.2dacr.azurecr.io/product-service:latest ./backend/product_service
        docker build -t 10.2dacr.azurecr.io/order-service:latest ./backend/order_service
        docker push 10.2dacr.azurecr.io/frontend:latest
        docker push 10.2dacr.azurecr.io/customer-service:latest
        docker push 10.2dacr.azurecr.io/product-service:latest
        docker push 10.2dacr.azurecr.io/order-service:latest